# Generated by Django 4.2.17 on 2025-03-21 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('task_title', models.CharField(max_length=255)),
                ('task_description', models.TextField()),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('work_submission', models.FileField(blank=True, null=True, upload_to='work_submissions/')),
                ('report', models.TextField(blank=True, null=True)),
                ('learnings', models.TextField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_updates', to='intern.intern')),
            ],
        ),
    ]
