# Generated by Django 4.2.17 on 2025-03-21 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_dailyworkupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyworkupdate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dailyworkupdate',
            name='work_submission',
        ),
        migrations.AlterField(
            model_name='dailyworkupdate',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.intern'),
        ),
        migrations.CreateModel(
            name='WorkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='work_submissions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='intern.dailyworkupdate')),
            ],
        ),
    ]
