# Generated by Django 4.2.17 on 2025-03-05 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptitude_score', models.FloatField(blank=True, null=True)),
                ('gd1_attendance', models.BooleanField(default=False)),
                ('gd1_marks', models.FloatField(blank=True, null=True)),
                ('gd2_attendance', models.BooleanField(default=False)),
                ('gd2_marks', models.FloatField(blank=True, null=True)),
                ('fees_paid', models.BooleanField(default=False)),
                ('technical_marks', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.application')),
            ],
        ),
    ]
