# Generated by Django 4.2.17 on 2025-03-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperformance',
            name='batch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
