# Generated by Django 4.2.17 on 2025-03-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userperformance_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperformance',
            name='aptitude_score',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userperformance',
            name='gd1_marks',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userperformance',
            name='gd2_marks',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userperformance',
            name='technical_marks',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
