# Generated by Django 4.2.17 on 2025-03-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_userperformance_aptitude_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='passport_photo',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.URLField(default=''),
        ),
    ]
