# Generated by Django 4.2.17 on 2025-03-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_transaction_options_transaction_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Credit Card', 'Credit Card'), ('UPI', 'UPI'), ('Other', 'Other')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default=None, max_length=10),
        ),
    ]
