# Generated by Django 4.2.17 on 2025-03-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_transaction_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='transaction_documents/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10),
        ),
    ]
