# Generated by Django 4.2.17 on 2025-03-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_transaction_document_alter_transaction_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
