# Generated by Django 4.2.17 on 2025-03-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_candidateperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('meeting', 'Meeting'), ('deadline', 'Deadline'), ('event', 'Event'), ('update', 'Update')], default='general', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_important', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, help_text='Optional link for more details', null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
